### ISSUE TITLE
File Naming Convention LOGIC

### ISSUE THREAD

**Issue by Science2Technology** [USB-Data-Logger/PythonBasedPCapp#2]
In this I explain why I am set on ONE specific FILE NAMEING 
Core is user must have minilam input to reduce HUMAN ERROR 
Must maintain  file sorting  even if File META DATA layer is remove 
(Copy pasting different drive  or uploading the file )
 
Soloutin is 
YYYY-MM-DD HH.MM.SS.MS sufix.csv 

Desing is so time and date is easly HUMAN readable 
"-" for DATE "." for TIME  & " " in between so it stops 
widows courseor when moving using ctrl+shift arrow

ms is bit much but why NOT 

Sufix so user input but it they dont its still sortable 
and no WIP 1 or WIP 2 or NEW TRY 3 or hu lu luuu  

![Image](https://github.com/USB-Data-Logger/PythonBasedPCapp/assets/151446106/6f817065-becd-4e6c-8c6a-d85b38a4896d)

So I working on it as of now I cant just give " " before 
user input sufix without a random "." coming and trying
to removing it removes it from HH.MM.SS.MS

**Comment by Science2Technology** [comment]
Name Fixed 
![Image](https://github.com/USB-Data-Logger/PythonBasedPCapp/assets/151446106/920fc4f1-6284-462c-aa0f-8b2a25a65e4e)

**Comment by thepratham81** [comment]
Resolved
